// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheGameCave.WebAPI.Data;

namespace TheGameCave.WebAPI.Migrations
{
    [DbContext(typeof(TheGameCaveContext))]
    [Migration("20191121073839_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheGameCave.Lib.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dice"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Movie / TV theme"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Party games"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Trivia"
                        });
                });

            modelBuilder.Entity("TheGameCave.Lib.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<string>("Description");

                    b.Property<int>("Language");

                    b.Property<int>("MinimumAge");

                    b.Property<string>("Name");

                    b.Property<string>("NumberOfPlayers");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(250);

                    b.Property<string>("PlayingTime");

                    b.Property<decimal>("Price");

                    b.Property<int>("ProductType");

                    b.Property<int>("PublisherId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            Description = "Mansions of Madness: Second Edition is a fully cooperative, app-driven board game of horror and mystery for one to five players that takes place in the same universe as Eldritch Horror and Elder Sign. Let the immersive app guide you through the veiled streets of Innsmouth and the haunted corridors of Arkham's cursed mansions as you search for answers and respite. Eight brave investigators stand ready to confront four scenarios of fear and mystery, collecting weapons, tools, and information, solving complex puzzles, and fighting monsters, insanity, and death. Open the door and step inside these hair-raising Mansions of Madness: Second Edition. It will take more than just survival to conquer the evils terrorizing this town.",
                            Language = 0,
                            MinimumAge = 14,
                            Name = "Mansions of Madness: Second Edition",
                            NumberOfPlayers = "1-5",
                            PhotoUrl = "mansionsofmadness2.jpg",
                            PlayingTime = "120-180",
                            Price = 89.95m,
                            ProductType = 0,
                            PublisherId = 2
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 4,
                            Description = "Something evil stirs in Arkham, and only you can stop it. Blurring the traditional lines between roleplaying and card game experiences, Arkham Horror: The Card Game is a Living Card Game of Lovecraftian mystery, monsters, and madness!",
                            Language = 0,
                            MinimumAge = 14,
                            Name = "Arkham Horror: The Card Game",
                            NumberOfPlayers = "1-2",
                            PhotoUrl = "arkhamhorrorcardgame.jpg",
                            PlayingTime = "60-120",
                            Price = 39.95m,
                            ProductType = 1,
                            PublisherId = 2
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 4,
                            Description = "Eldritch Horror is a cooperative game of terror and adventure in which one to eight players take the roles of globetrotting investigators working to solve mysteries, gather clues, and protect the world from an Ancient One – that is, an elder being intent on destroying our world. Each Ancient One comes with its own unique decks of Mystery and Research cards, which draw you deeper into the lore surrounding each loathsome creature. Discover the true name of Azathoth or battle Cthulhu on the high seas.",
                            Language = 0,
                            MinimumAge = 14,
                            Name = "Eldritch Horror",
                            NumberOfPlayers = "1-8",
                            PhotoUrl = "eldritchhorror.jpg",
                            PlayingTime = "120-240",
                            Price = 59.95m,
                            ProductType = 0,
                            PublisherId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Description = "Your last village was ransacked by barbarians. You barely had time to pick up the baby and your favorite fishing pole before they started the burning and pillaging. You wandered over a cruel desert, braved frozen peaks, and even paddled a log across a rough sea, kicking at the sharks whenever they got too close, the baby strapped tightly to your back.",
                            Language = 0,
                            MinimumAge = 13,
                            Name = "Above and Below",
                            NumberOfPlayers = "2-4",
                            PhotoUrl = "aboveandbelow.jpg",
                            PlayingTime = "90",
                            Price = 39.95m,
                            ProductType = 0,
                            PublisherId = 3
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Description = "Stuffed Fables is an unusual adventure game in which players take on the roles of brave stuffies seeking to save the child they love from a scheming, evil mastermind. Make daring melee attacks, leap across conveyor belts, or even steer a racing wagon down a peril-filled hill. The game delivers a thrilling narrative driven by player choices. Players explore a world of wonder and danger, unlocking curious discoveries. The chapters of Stuffed Fables explore the many milestones of a child's life, creating a memorable tale ideal for families, as well as groups of adults who haven't forgotten their childlike sense of wonder.",
                            Language = 0,
                            MinimumAge = 7,
                            Name = "Stuffed Fables",
                            NumberOfPlayers = "2-4",
                            PhotoUrl = "stuffedfables.jpg",
                            PlayingTime = "60-90",
                            Price = 55.95m,
                            ProductType = 0,
                            PublisherId = 4
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Description = "Robinson Crusoe: Adventures on the Cursed Island is an epic game from Portal. You will build a shelter, palisade, weapons, you will create tools like axes, knives, sacks, you will do everything you can to… to survive. You will have to find food, fight wild beasts, protect yourself from weather changes…",
                            Language = 0,
                            MinimumAge = 14,
                            Name = "Robinson Crusoe: Adventures on the Cursed Island",
                            NumberOfPlayers = "1-4",
                            PhotoUrl = "robinsoncrusoe.jpg",
                            PlayingTime = "60-120",
                            Price = 36.95m,
                            ProductType = 0,
                            PublisherId = 5
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            Description = "Draft dice and use the tools-of-the-trade in Sagrada to carefully construct your stained glass window masterpiece.<br><br> In more detail, each player builds a stained glass window by building up a grid of dice on their player board. Each board has some restrictions on which color or shade (value) of die can be placed there. Dice of the same shade or color may never be placed next to each other. Dice are drafted in player order, with the start player rotating each round, snaking back around after the last player drafts two dice. Scoring is variable per game based on achieving various patterns and varieties of placement...as well as bonus points for dark shades of a particular hidden goal color.",
                            Language = 0,
                            MinimumAge = 14,
                            Name = "Sagrada",
                            NumberOfPlayers = "1-4",
                            PhotoUrl = "sagrada.jpg",
                            PlayingTime = "30-45",
                            Price = 29.95m,
                            ProductType = 0,
                            PublisherId = 6
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 2,
                            Description = "Choose your dice well in Clever to enter them into the matching colored area, put together tricky chain-scoring opportunities, and rack up the points. The dice you don't use are as important as what you do because every die that's smaller than the chosen one can be used by the other players, keeping everyone in the game at all times.",
                            Language = 1,
                            MinimumAge = 8,
                            Name = "Clever",
                            NumberOfPlayers = "1-4",
                            PhotoUrl = "mansionsofmadness2.jpg",
                            PlayingTime = "30",
                            Price = 13.95m,
                            ProductType = 0,
                            PublisherId = 7
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Description = "Escape: The Curse of the Temple is a cooperative game in which players must escape (yes...) from a temple (yes...) which is cursed (yes...) before the temple collapses and kills one or more explorers, thereby causing everyone to lose.",
                            Language = 0,
                            MinimumAge = 8,
                            Name = "Escape: The Curse of the Temple",
                            NumberOfPlayers = "1-5",
                            PhotoUrl = "escapethecurseofthetemple.jpg",
                            PlayingTime = "10",
                            Price = 43.95m,
                            ProductType = 0,
                            PublisherId = 8
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Description = "A group of poor explorers hoping to get rich quickly heads out to recover treasures from some undersea ruins. They're all rivals, but their budgets force them all to share a single rented submarine. In the rented submarine, they all have to share a single tank of air, as well. If they don't get back to the sub before they run out of air, they'll drop all their treasure. Now it's time to see who can bring home the greatest riches.",
                            Language = 0,
                            MinimumAge = 8,
                            Name = "Deep Sea Adventure",
                            NumberOfPlayers = "2-6",
                            PhotoUrl = "deepseaadventure.jpg",
                            PlayingTime = "30",
                            Price = 9.95m,
                            ProductType = 0,
                            PublisherId = 9
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 3,
                            Description = "Spirit Island is a complex and thematic cooperative game about defending your island home from colonizing Invaders. Players are different spirits of the land, each with its own unique elemental powers. Every turn, players simultaneously choose which of their power cards to play, paying energy to do so. Using combinations of power cards that match a spirit's elemental affinities can grant free bonus effects. Faster powers take effect immediately, before the Invaders spread and ravage, but other magics are slower, requiring forethought and planning to use effectively. In the Spirit phase, spirits gain energy, and choose how / whether to Grow: to reclaim used power cards, to seek for new power, or to spread presence into new areas of the island.",
                            Language = 0,
                            MinimumAge = 13,
                            Name = "Spirit Island",
                            NumberOfPlayers = "1-4",
                            PhotoUrl = "spiritisland.jpg",
                            PlayingTime = "90-120",
                            Price = 79.95m,
                            ProductType = 0,
                            PublisherId = 10
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 3,
                            Description = "Crossing into the Land of 1001 Nights, your caravan arrives at the fabled Sultanate of Naqala. The old sultan just died and control of Naqala is up for grabs! The oracles foretold of strangers who would maneuver the Five Tribes to gain influence over the legendary city-state. Will you fulfill the prophecy? Invoke the old Djinns and move the Tribes into position at the right time, and the Sultanate may become yours!",
                            Language = 0,
                            MinimumAge = 13,
                            Name = "Five Tribes",
                            NumberOfPlayers = "2-4",
                            PhotoUrl = "fivetribes.jpg",
                            PlayingTime = "40-80",
                            Price = 44.95m,
                            ProductType = 0,
                            PublisherId = 11
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 3,
                            Description = "In the second edition of A Game of Thrones: The Board Game, three to six players take on the roles of the great Houses of the Seven Kingdoms of Westeros, as they vie for control of the Iron Throne through the use of diplomacy and warfare. Based on the best-selling A Song of Ice and Fire series of fantasy novels by George R.R. Martin, A Game of Thrones is an epic board game in which it will take more than military might to win. Will you take power through force, use honeyed words to coerce your way onto the throne, or rally the townsfolk to your side? Through strategic planning, masterful diplomacy, and clever card play, spread your influence over Westeros!",
                            Language = 0,
                            MinimumAge = 14,
                            Name = "A Game of Thrones: The Board Game (Second Edition)",
                            NumberOfPlayers = "3-6",
                            PhotoUrl = "gameofthronesboardgame.jpg",
                            PlayingTime = "120-240",
                            Price = 64.95m,
                            ProductType = 0,
                            PublisherId = 2
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 3,
                            Description = "The Lord of the Rings: The Card Game is a cooperative adventure game in which the players attempt to complete a scenario, each with three heroes of their choice and a deck of allies, events and attachments to support them. Each round, players send their heroes and allies to quest or to fight with enemies that engage them. However, as the heroes and allies exhaust after questing, defending, or attacking, the players' options are typically insufficient to deal with everything at once. Therefore, players need to determine whether it is more urgent to quest and make progress in the scenario while the enemy forces gain power, or to take down enemies while making no progress, not knowing what will come next.",
                            Language = 0,
                            MinimumAge = 13,
                            Name = "The Lord of the Rings: The Card Game",
                            NumberOfPlayers = "1-2",
                            PhotoUrl = "lordoftheringscardgame.jpg",
                            PlayingTime = "30-60",
                            Price = 42.95m,
                            ProductType = 1,
                            PublisherId = 2
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 5,
                            Description = "Star Wars: Rebellion is a board game of epic conflict between the Galactic Empire and Rebel Alliance for two to four players.<br><br>Experience the Galactic Civil War like never before. In Rebellion, you control the entire Galactic Empire or the fledgling Rebel Alliance. You must command starships, account for troop movements, and rally systems to your cause. Given the differences between the Empire and Rebel Alliance, each side has different win conditions, and you'll need to adjust your play style depending on who you represent.",
                            Language = 0,
                            MinimumAge = 14,
                            Name = "Star Wars: Rebellion",
                            NumberOfPlayers = "2-4",
                            PhotoUrl = "starwarsrebellion.jpg",
                            PlayingTime = "180-240",
                            Price = 99.95m,
                            ProductType = 0,
                            PublisherId = 2
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 5,
                            Description = "Battlestar Galactica: The Board Game is an exciting game of mistrust, intrigue, and the struggle for survival. Based on the epic and widely-acclaimed Sci Fi Channel series, Battlestar Galactica: The Board Game puts players in the role of one of ten of their favorite characters from the show. Each playable character has their own abilities and weaknesses, and must all work together in order for humanity to have any hope of survival. However, one or more players in every game secretly side with the Cylons. Players must attempt to expose the traitor while fuel shortages, food contaminations, and political unrest threatens to tear the fleet apart.",
                            Language = 0,
                            MinimumAge = 14,
                            Name = "Battlestar Galactica: The Board Game",
                            NumberOfPlayers = "3-6",
                            PhotoUrl = "battlestargalacticaboardgame.jpg",
                            PlayingTime = "120-180",
                            Price = 49.95m,
                            ProductType = 0,
                            PublisherId = 2
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 5,
                            Description = "The forces of evil are threatening to overrun Hogwarts castle in Harry Potter: Hogwarts Battle, a cooperative deck-building game, and it's up to four students to ensure the safety of the school by defeating villains and consolidating their defenses. In the game, players take on the role of a Hogwarts student: Harry, Ron, Hermione or Neville, each with their own personal deck of cards that's used to acquire resources.",
                            Language = 0,
                            MinimumAge = 11,
                            Name = "Harry Potter: Hogwarts Battle",
                            NumberOfPlayers = "2-4",
                            PhotoUrl = "harrypotterhogwartsbattle.jpg",
                            PlayingTime = "30-60",
                            Price = 49.95m,
                            ProductType = 1,
                            PublisherId = 12
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 5,
                            Description = "Legendary Encounters: An Alien Deck Building Game, based on the four movies of the Alien series, is a fully cooperative game with original art. While based on the Marvel superheroes version of Legendary, the two games will be compatible but cannot be fully integrated.<br><br>Legendary Encounters is a deck-building game in the same family as Legendary: A Marvel Deck Building Game, but now players must cooperate in order to survive against hordes of aliens. Taking on the role of protagonists such as Ripley, Dallas, Bishop and Corporal Hicks, players take turns recruiting cards for their deck from a central selection in order to improve their deck and defeat Xenomorph cards that are added to the central game board.",
                            Language = 0,
                            MinimumAge = 17,
                            Name = "Legendary Encounters: An Alien Deck Building Game",
                            NumberOfPlayers = "1-5",
                            PhotoUrl = "legendaryencounters-alien.jpg",
                            PlayingTime = "30-60",
                            Price = 59.95m,
                            ProductType = 1,
                            PublisherId = 13
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 6,
                            Description = "In Codenames, two teams compete to see who can make contact with all of their agents first. Spymasters give one-word clues that can point to multiple words on the board. Their teammates try to guess words of the right color while avoiding those that belong to the opposing team. And everyone wants to avoid the assassin.",
                            Language = 0,
                            MinimumAge = 14,
                            Name = "Codenames",
                            NumberOfPlayers = "2-8",
                            PhotoUrl = "codenames.jpg",
                            PlayingTime = "15",
                            Price = 17.95m,
                            ProductType = 1,
                            PublisherId = 14
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 6,
                            Description = "Sushi Go Party!, an expanded version of the best-selling card game Sushi Go!, is a party platter of mega maki, super sashimi, and endless edamame. You still earn points by picking winning sushi combos, but now you can customize each game by choosing à la carte from a menu of more than twenty delectable dishes. What's more, up to eight players can join in on the sushi-feast. Let the good times roll!",
                            Language = 0,
                            MinimumAge = 8,
                            Name = "Sushi Go Party!",
                            NumberOfPlayers = "2-8",
                            PhotoUrl = "sushigoparty.jpg",
                            PlayingTime = "20",
                            Price = 22.95m,
                            ProductType = 1,
                            PublisherId = 14
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 6,
                            Description = "Exploding Kittens is a kitty-powered version of Russian Roulette. Players take turns drawing cards until someone draws an exploding kitten and loses the game. The deck is made up of cards that let you avoid exploding by peeking at cards before you draw, forcing your opponent to draw multiple cards, or shuffling the deck.",
                            Language = 0,
                            MinimumAge = 7,
                            Name = "Exploding Kittens: Party Pack",
                            NumberOfPlayers = "2-10",
                            PhotoUrl = "explodingkittenspartypack.jpg",
                            PlayingTime = "15",
                            Price = 34.95m,
                            ProductType = 1,
                            PublisherId = 15
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 6,
                            Description = "Game play in Dixit Odyssey matches that of Dixit: Each turn one player is the storyteller. This player secretly chooses one card in his hand, then gives a word or sentence to describe this card—but not too obviously. Each other player chooses a card in hand that matches this word/sentence and gives it to the storyteller. The storyteller then lays out the cards, and all other players vote on which card belongs to the storyteller. If no one or everyone guesses the storyteller's card, the storyteller receives no points and all players receive two; otherwise the storyteller and the correct guesser(s) each receive three points. Players score one point for each vote their image receives. Players refill their hands, and the next player becomes the storyteller. When the deck runs out, the player with the most points wins.",
                            Language = 0,
                            MinimumAge = 8,
                            Name = "Dixit: Odyssey",
                            NumberOfPlayers = "3-12",
                            PhotoUrl = "dixitodyssey.jpg",
                            PlayingTime = "30",
                            Price = 26.95m,
                            ProductType = 1,
                            PublisherId = 16
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 7,
                            Description = "In the 2400s, mankind begins to terraform the planet Mars. Giant corporations, sponsored by the World Government on Earth, initiate huge projects to raise the temperature, the oxygen level, and the ocean coverage until the environment is habitable. In Terraforming Mars, you play one of those corporations and work together in the terraforming process, but compete for getting victory points that are awarded not only for your contribution to the terraforming, but also for advancing human infrastructure throughout the solar system, and doing other commendable things.",
                            Language = 0,
                            MinimumAge = 12,
                            Name = "Terraforming Mars",
                            NumberOfPlayers = "1-5",
                            PhotoUrl = "terraformingmars.jpg",
                            PlayingTime = "120",
                            Price = 69.95m,
                            ProductType = 0,
                            PublisherId = 1
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 7,
                            Description = "Scythe is an engine-building game set in an alternate-history 1920s period. It is a time of farming and war, broken hearts and rusted gears, innovation and valor. In Scythe, each player represents a character from one of five factions of Eastern Europe who are attempting to earn their fortune and claim their faction's stake in the land around the mysterious Factory. Players conquer territory, enlist new recruits, reap resources, gain villagers, build structures, and activate monstrous mechs.",
                            Language = 0,
                            MinimumAge = 14,
                            Name = "Scythe",
                            NumberOfPlayers = "1-5",
                            PhotoUrl = "scythe.jpg",
                            PlayingTime = "90-115",
                            Price = 79.95m,
                            ProductType = 0,
                            PublisherId = 17
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 7,
                            Description = "The T.I.M.E Agency protects humanity by preventing temporal faults and paradoxes from threatening the fabric of our universe. As temporal agents, you and your team will be sent into the bodies of beings from different worlds or realities to successfully complete the missions given to you. Failure is impossible, as you will be able to go back in time as many times as required.",
                            Language = 0,
                            MinimumAge = 12,
                            Name = "T.I.M.E Stories",
                            NumberOfPlayers = "2-4",
                            PhotoUrl = "timestories.jpg",
                            PlayingTime = "90",
                            Price = 37.95m,
                            ProductType = 0,
                            PublisherId = 18
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 8,
                            Description = "Game of Thrones: The Trivia Game lets you use your knowledge to compete for the Iron Throne. You and your friends answer questions about the first four seasons of the hit HBO series in order to conquer key locations in Westeros. Whoever controls the most locations in the Seven Kingdoms wins! Choose more difficult questions to immediately gain more control over a location, accumulate resources to earn the favor of iconic characters, and cunningly make and break alliances with other players. Questions are organized by season to ensure that your game is free from spoilers. With over 1,200 questions included, you are certain to find fresh challenges and learn new details about Westeros with every game.",
                            Language = 0,
                            MinimumAge = 18,
                            Name = "Game of Thrones: The Trivia Game",
                            NumberOfPlayers = "2-4",
                            PhotoUrl = "gameofthronestrivia.jpg",
                            PlayingTime = "30-60",
                            Price = 42.95m,
                            ProductType = 1,
                            PublisherId = 2
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 8,
                            Description = "In the trivia game iKNOW, you get to test what other players know while trying to score for yourself. The game includes 1,600 questions in four categories, and each question comes with three hints at three levels of difficulty that reveal the answer piece by piece. Do you think you'll know the answer first – or should you let other players give the question a try?",
                            Language = 1,
                            MinimumAge = 14,
                            Name = "iKNOW",
                            NumberOfPlayers = "2-6",
                            PhotoUrl = "iknow.jpg",
                            PlayingTime = "60",
                            Price = 29.95m,
                            ProductType = 1,
                            PublisherId = 19
                        });
                });

            modelBuilder.Entity("TheGameCave.Lib.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Intrafin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fantasy Flight Games"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Red Raven Games"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Plaid Hat Games"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Portal Games"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Matagot"
                        },
                        new
                        {
                            Id = 7,
                            Name = "999 Games"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Queen Games"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Oink Games"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Greater Than Games"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Days of Wonder"
                        },
                        new
                        {
                            Id = 12,
                            Name = "USAopoly"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Upper Deck Entertainment"
                        },
                        new
                        {
                            Id = 14,
                            Name = "White Goblin Games"
                        },
                        new
                        {
                            Id = 15,
                            Name = "The Oatmeal"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Libellud"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Stonemaier Games"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Space Cowboys"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Tactic"
                        });
                });

            modelBuilder.Entity("TheGameCave.Lib.Models.Product", b =>
                {
                    b.HasOne("TheGameCave.Lib.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TheGameCave.Lib.Models.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
