// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TheGameCave.WebAPI.Data;

namespace TheGameCave.WebAPI.Migrations
{
    [DbContext(typeof(TheGameCaveContext))]
    partial class TheGameCaveContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TheGameCave.WebAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dice"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fantasy"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Horror"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Movie / TV theme"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Party games"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Trivia"
                        });
                });

            modelBuilder.Entity("TheGameCave.WebAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId");

                    b.Property<string>("Description");

                    b.Property<int>("Language");

                    b.Property<int>("MinimumAge");

                    b.Property<string>("Name");

                    b.Property<string>("NumberOfPlayers");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(250);

                    b.Property<string>("PlayingTime");

                    b.Property<decimal>("Price");

                    b.Property<int>("ProductType");

                    b.Property<int>("PublisherId");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PublisherId");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 4,
                            Description = "Mansions of Madness: Second Edition is a fully cooperative, app-driven board game of horror and mystery for one to five players that takes place in the same universe as Eldritch Horror and Elder Sign. Let the immersive app guide you through the veiled streets of Innsmouth and the haunted corridors of Arkham's cursed mansions as you search for answers and respite. Eight brave investigators stand ready to confront four scenarios of fear and mystery, collecting weapons, tools, and information, solving complex puzzles, and fighting monsters, insanity, and death. Open the door and step inside these hair-raising Mansions of Madness: Second Edition. It will take more than just survival to conquer the evils terrorizing this town.",
                            Language = 0,
                            MinimumAge = 14,
                            Name = "Mansions of Madness: Second Edition",
                            NumberOfPlayers = "1-5",
                            PhotoUrl = "mansionsofmadness2.jpg",
                            PlayingTime = "120-180",
                            Price = 89.95m,
                            ProductType = 0,
                            PublisherId = 2
                        });
                });

            modelBuilder.Entity("TheGameCave.WebAPI.Models.Publisher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Publisher");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Intrafin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Fantasy Flight Games"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Red Raven Games"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Plaid Hat Games"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Portal Games"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Matagot"
                        },
                        new
                        {
                            Id = 7,
                            Name = "999 Games"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Queen Games"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Oink Games"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Greater Than Games"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Days of Wonder"
                        },
                        new
                        {
                            Id = 12,
                            Name = "USAopoly"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Upper Deck Entertainment"
                        },
                        new
                        {
                            Id = 14,
                            Name = "White Goblin Games"
                        },
                        new
                        {
                            Id = 15,
                            Name = "The Oatmeal"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Libellud"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Stonemaier Games"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Space Cowboys"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Tactic"
                        });
                });

            modelBuilder.Entity("TheGameCave.WebAPI.Models.Product", b =>
                {
                    b.HasOne("TheGameCave.WebAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("TheGameCave.WebAPI.Models.Publisher", "Publisher")
                        .WithMany()
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
